name: Renew Trustlist DE

on:
  schedule: # every day at 3:37 and 13:37 UTC
    - cron: '0 5,10,15,20 * * *'
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download a file
        run: curl https://de.dscg.ubirch.com/trustList/DSC -o trustlist-de.json
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github action download trustlist
          message: 'Update Trustlist DE'
          add: 'trustlist-de.json'
