name: Renew Trustlist IT

on:
  schedule:
    - cron: '0 5,10,15,20 * * *'
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/trustlist_it/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: prepare node  
        run: npm install
      - name: get script from source
        run: curl -O https://raw.githubusercontent.com/ministero-salute/dcc-utils/master/examples/fetch_certificates.js
      - name: patch script output path
        run: awk '!/^\/\// && /const OUTFILE =/ {$0="//"$0"\nconst OUTFILE = '../../trustlist_it.json';"} {print $0}' > tmp.js
      - name: get trustlist IT
        run: node fetch_certificates.js
      - name: debug
        run: awk '/const OUTFILE =/ {print $0}' fetch_certificates.js
      
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github action download trustlist
          message: 'Update Trustlist IT'
          add: "['trustlist_it.json', 'trustlist_it.min.json', '*.js']"
